### PR TITLE
Utilities pull request

### PR DESCRIPTION
**Pull request by walksanatora**
adds various mods
* Lootr. makes loot chest/barrels/shulkers per-player so multiple people can get resources from one chest
* Heracles. Quest (may be removed if we don't have a quest line later)
* Argonauts. Teams
* Cadmus. Land claiming and Chunk loading
* Prometheus. administration and permissions made easy
* Jade + Jade Additons. every modpack needs a WAILIA mod, additions adds more support for other mods
* Inventory Profiles Next. adds inventory sorting. hold and drag moving items and other inventory tweaks (is also configurable)
* Controlling. adds search bar to the keybinds screen and a list of un-used keys (can also search by category, or key, or keybind name)

### CODE REVIEW

**Review by electron271 — CHANGES_REQUESTED** [review]
- [x] Lootr. works fine
- [x] Heracles. works fine
- [ ] Argonauts. doesnt work, either it also has to be client sided or its a issue on my part
- [ ] Cadmus. same as above
- [ ] Prometheus. commands work fine but i cant seem to find the gui, also possibly a issue on my part
- [x] Jade + Jade Additons. works fine
- [ ] Inventory Profiles Next. gui conflicts with emi image
- [x] Controlling. works fine

**Comment by electron271** [comment]
testing argonauts, cadmus, and prometheus with client side enabled

**Comment by electron271** [comment]
works now but it turns out it was probably user error

testing without client side enabled

**Comment by electron271** [comment]
image
nvm

**Comment by walksanatora** [comment]
switched to mouse-wheelie which has no buttons but instead uses keybinds

**Comment by walksanatora** [comment]
undog

**Comment by electron271** [comment]
fixed (probably) merge conflict

**Comment by electron271** [comment]
fixed, im going to run a new test

**Review by electron271 — APPROVED** [review]
- [x] Lootr. works fine
- [x] Heracles. works fine
- [x] Argonauts. works fine
- [x] Cadmus. works fine
- [x] Prometheus. works fine
- [x] Jade + Jade Additons. works fine
- [x] Mouse Wheelie. works fine
- [x] Controlling. works fine

**Pull request merged**
